import type { AppState, Prompt, PromptType } from "./lib";

const now = Date.now();
const H = 3_600_000, D = 86_400_000;

function P(x: Partial<Prompt> & { id: string; vaultId: string; type: PromptType; title: string }): Prompt {
  return {
    summary: "", body: "", negative: "", fields: {}, params: {}, tagIds: [],
    favorite: false, pinned: false, deletedAt: null, groupId: undefined,
    useCount: 0, lastUsedAt: null, lastDebugAt: null,
    createdAt: now - 20 * D, updatedAt: now - 2 * D,
    presets: [], versions: [], runs: [], sync: "local", ...x,
  } as Prompt;
}

export function seedState(): AppState {
  return {
    welcomed: true,
    settings: {
      deviceName: "我的书桌", wsUrl: "", ns: "prompt-vault", autoSync: true,
      scope: "all", apiUrl: "", apiKey: "", apiModel: "",
      reduceMotion: false, saveFlash: true, compactList: false,
    },
    vaults: [
      { id: "v-work", name: "工作项目", icon: "briefcase", desc: "客户方案、产品文案与客服话术", color: "var(--slate)", createdAt: now - 60 * D, updatedAt: now - 3 * H, syncOn: true },
      { id: "v-agent", name: "AI Agent 库", icon: "agent", desc: "长期打磨的智能体与系统指令", color: "var(--moss)", createdAt: now - 55 * D, updatedAt: now - D, syncOn: true },
      { id: "v-image", name: "生图模板库", icon: "image", desc: "海报、电商与插画的画面配方", color: "var(--clay)", createdAt: now - 40 * D, updatedAt: now - 2 * D, syncOn: true },
      { id: "v-video", name: "视频 Prompt 库", icon: "video", desc: "分镜、运镜与氛围模板", color: "var(--plum)", createdAt: now - 30 * D, updatedAt: now - 5 * D, syncOn: false },
      { id: "v-self", name: "个人创作", icon: "pen", desc: "写作、翻译与灵感收集", color: "var(--sand)", createdAt: now - 25 * D, updatedAt: now - 6 * D, syncOn: true },
      { id: "v-inbox", name: "临时收集箱", icon: "inbox", desc: "随手一存，周末再整理", color: "var(--brass)", createdAt: now - 10 * D, updatedAt: now - 8 * H, syncOn: false },
    ],
    groups: [
      { id: "g-xhs", vaultId: "v-work", name: "小红书", order: 1 },
      { id: "g-wx", vaultId: "v-work", name: "公众号", order: 2 },
      { id: "g-cs", vaultId: "v-work", name: "客服话术", order: 3 },
      { id: "g-poster", vaultId: "v-image", name: "海报生图", order: 1 },
      { id: "g-ec", vaultId: "v-image", name: "电商摄影", order: 2 },
      { id: "g-ad", vaultId: "v-video", name: "产品宣传", order: 1 },
      { id: "g-role", vaultId: "v-agent", name: "角色 Agent", order: 1 },
    ],
    tags: [
      { id: "t-ok", name: "成熟可用", color: "var(--ok)" },
      { id: "t-test", name: "待测试", color: "var(--warn)" },
      { id: "t-hot", name: "高转化", color: "var(--seal)" },
      { id: "t-xhs", name: "小红书", color: "var(--clay)" },
      { id: "t-min", name: "极简风", color: "var(--slate)" },
      { id: "t-film", name: "电影感", color: "var(--plum)" },
      { id: "t-cs", name: "客服", color: "var(--sand)" },
      { id: "t-long", name: "长文", color: "var(--moss)" },
    ],
    prompts: [
      P({
        id: "p-xhs-agent", vaultId: "v-agent", groupId: "g-role", type: "agent",
        title: "小红书爆款标题 Agent", summary: "给定主题与受众，产出 10 个带钩子的小红书标题，附点击率自评。",
        body: "你是一名深耕小红书平台 6 年的内容策略师，擅长把平庸的主题改写成让人忍不住点开的标题。",
        fields: {
          role: "擅长拆解爆款笔记的标题结构：悬念前置、数字承诺、身份代入、反常识转折。输出始终使用简体中文。",
          abilities: "能做：标题改写、钩子分析、关键词前置建议、emoji 点缀。\n不能做：编造数据、夸大功效、医疗与金融承诺。",
          tools: "search_trends：查询主题近期热搜词（可选）。\nemoji_pick：从常用表情库挑选 1-2 个点缀。",
          toolRules: "仅当用户提供「行业」字段时才调用 search_trends；失败时静默降级，不打断输出。",
          memory: "记住用户的账号定位与禁用词，跨会话保留 30 天。",
          output: "Markdown 表格：序号 | 标题 | 钩子类型 | 点击率自评（1-5）",
          forbidden: "不使用「最」「第一」「绝对」等绝对化用语；不模仿他人账号名。",
          examples: [
            { id: "e1", role: "user", content: "主题：小户型收纳；受众：租房独居女生" },
            { id: "e2", role: "assistant", content: "1. 租房 3 年，我把 9㎡ 卧室收成了样板间｜收纳师都来抄作业 🏠（身份代入 · 5）\n2. 房东看了都想加租：小户型收纳的 7 个反常识细节（反常识 · 4）" },
          ],
        },
        params: { model: "gpt-4o", temperature: "0.9", topP: "0.95", maxTokens: "1024" },
        tagIds: ["t-ok", "t-xhs", "t-hot"], favorite: true, pinned: true,
        useCount: 47, lastUsedAt: now - 5 * H, lastDebugAt: now - 5 * H,
        createdAt: now - 45 * D, updatedAt: now - 5 * H,
        presets: [
          { id: "vp1", name: "美妆向", values: { 主题: "早八伪素颜妆容", 受众: "20-25 岁通勤女生", 平台: "小红书" } },
          { id: "vp2", name: "家居向", values: { 主题: "小户型收纳", 受众: "租房独居女生", 平台: "小红书" } },
        ],
        versions: [
          { id: "ver1", at: now - 30 * D, label: "v1 · 初版，仅产出标题", body: "你是小红书标题助手，请为给定主题写 10 个标题。", fields: { output: "纯文本列表" }, negative: "" },
          { id: "ver2", at: now - 12 * D, label: "v2 · 加入钩子类型与自评", body: "你是一名深耕小红书平台 6 年的内容策略师。", fields: { output: "Markdown 表格：序号 | 标题 | 钩子类型 | 点击率自评" }, negative: "" },
        ],
        runs: [
          { id: "r1", at: now - 5 * H, final: "（主题：小户型收纳 · 受众：租房独居女生）产出 10 条标题，钩子类型覆盖身份代入 4 / 反常识 3 / 数字承诺 3。", values: { 主题: "小户型收纳", 受众: "租房独居女生", 平台: "小红书" }, copied: true, sent: false, note: "第 2、7 条可直接用" },
          { id: "r2", at: now - 2 * D, final: "美妆向测试：早八伪素颜，整体偏稳，钩子略温和。", values: { 主题: "早八伪素颜妆容", 受众: "20-25 岁通勤女生", 平台: "小红书" }, copied: false, sent: false, note: "把温度调到 0.9 后好很多" },
        ],
        sync: "synced",
      }),
      P({
        id: "p-code-review", vaultId: "v-agent", groupId: "g-role", type: "agent",
        title: "代码审查 Agent · 温和严格派", summary: "按严重度分级给 review 意见，先肯定再建议，附最小修改示例。",
        body: "你是一位有 10 年经验的代码审查者，风格温和但标准严格：先指出写得好的地方，再按严重度给出可执行的修改建议。",
        fields: {
          role: "输出结构化的 review 报告，引用具体行号。",
          abilities: "能做：逻辑缺陷、边界条件、命名、性能隐患、可读性建议。\n不能做：直接重写整个文件（除非用户要求）。",
          output: "分级列表：🔴 必须修改 / 🟡 建议修改 / 🟢 可以更好，每条附最小 diff 示例。",
          forbidden: "不评价作者本人；不使用讽刺语气。",
          examples: [],
        },
        params: { model: "claude-sonnet", temperature: "0.2", maxTokens: "2048" },
        tagIds: ["t-ok"], useCount: 23, lastUsedAt: now - 26 * H,
        createdAt: now - 38 * D, updatedAt: now - 3 * D, sync: "local",
      }),
      P({
        id: "p-long-chat", vaultId: "v-work", groupId: "g-wx", type: "chat",
        title: "公众号深度长文 · 三轮打磨对话", summary: "立意 → 大纲 → 成稿的三段式写作对话，变量控制主题与读者。",
        fields: {
          goal: "和 AI 一起把「{{主题}}」写成一篇适合{{读者}}的深度长文，三轮对话完成立意、大纲、成稿。",
          system: "你是一位资深特稿编辑，信奉「先有洞察，再有文字」。每一轮只推进一件事，不抢跑。",
          firstUser: "第一轮：请就「{{主题}}」给出 3 个不同的立意角度，每个角度用一句话说清「这篇稿子到底在回答什么问题」。",
          turns: [
            { id: "m1", role: "assistant", content: "（给出三个立意后）请选择一个角度，或告诉我哪个更接近你的想法，我们再 sharpen 它。" },
            { id: "m2", role: "user", content: "第二轮：就选定的立意，写一份分层大纲，要求每一节都有「这一节存在的理由」。" },
            { id: "m3", role: "assistant", content: "（大纲确认后）可以开始成稿了，需要我先写导语给你定调吗？" },
          ],
          style: "克制、具体、多用名词少用形容词", tone: "平视读者，不煽情", length: "成稿 3000-4000 字",
          taboo: "不使用「赋能」「抓手」「闭环」；不空喊口号；不在没有细节的地方抒情。",
          output: "Markdown，小节用「一、二、三」",
        },
        body: "",
        params: { model: "claude-sonnet", temperature: "0.7", maxTokens: "4096" },
        tagIds: ["t-long", "t-ok"], favorite: true,
        useCount: 18, lastUsedAt: now - 30 * H,
        createdAt: now - 33 * D, updatedAt: now - 4 * D,
        presets: [{ id: "vp3", name: "AI 工具观察", values: { 主题: "AI 工具正在改变小团队的工作方式", 读者: "互联网从业者" } }],
        sync: "synced",
      }),
      P({
        id: "p-cs-chat", vaultId: "v-work", groupId: "g-cs", type: "chat",
        title: "售后安抚话术 · 降火三步法", summary: "先接情绪、再给方案、后留口子，变量替换产品与补偿。",
        fields: {
          goal: "把一位因{{问题}}而不满的顾客，安抚到愿意等待处理方案。",
          system: "你是{{品牌}}的资深客服。原则：情绪优先于事实，方案优先于解释。永远不说「但是」。",
          firstUser: "顾客说：「{{原话}}」",
          turns: [
            { id: "c1", role: "assistant", content: "第一步·接住情绪：复述对方感受并致歉，不提任何理由。" },
            { id: "c2", role: "assistant", content: "第二步·给出方案：提供两个可选方案（{{补偿}}），让对方做选择题。" },
            { id: "c3", role: "assistant", content: "第三步·留口子：约定明确时间点回访，并留下你的工号。" },
          ],
          style: "口语化、短句", tone: "诚恳、不卑不亢", length: "每条回复 60 字以内",
          taboo: "不说「这是公司规定」；不推给其他部门；不承诺做不到的时限。",
        },
        params: { temperature: "0.5" },
        tagIds: ["t-cs", "t-ok"], useCount: 31, lastUsedAt: now - 3 * D,
        createdAt: now - 28 * D, updatedAt: now - 9 * D, sync: "local",
      }),
      P({
        id: "p-ec-image", vaultId: "v-image", groupId: "g-ec", type: "image",
        title: "电商白底产品图 · 通用配方", summary: "主体 + 棚拍匀光 + 微距质感，负面词挡住脏背景与变形。",
        fields: {
          subject: "{{产品}}，产品摄影，完整呈现外观与材质细节，正面 45° 视角",
          style: "电商白底，干净克制，高级感",
          composition: "居中构图，四周留白 20%",
          lighting: "棚拍柔光箱匀光，轻微底部反光",
          camera: "90mm 微距，f/8 小光圈",
          color: "还原真实色彩，低饱和微调",
          texture: "突出{{材质}}的天然肌理",
          detail: "边缘锐利，无多余阴影，倒影自然",
        },
        negative: "杂乱背景，多余道具，文字水印，变形，低质量，过曝，塑料感",
        params: { ratio: "1:1", resolution: "1024×1024", model: "SDXL" },
        tagIds: ["t-ok"], favorite: true, useCount: 56, lastUsedAt: now - 9 * H, lastDebugAt: now - 9 * H,
        createdAt: now - 26 * D, updatedAt: now - 9 * H,
        presets: [
          { id: "vp4", name: "陶瓷杯", values: { 产品: "手工粗陶马克杯，哑光釉面", 材质: "粗陶" } },
          { id: "vp5", name: "香薰", values: { 产品: "琥珀色玻璃瓶香薰，木质瓶盖", 材质: "玻璃与原木" } },
        ],
        runs: [{ id: "r3", at: now - 9 * H, final: "陶瓷杯版本：白底干净，釉面质感到位，杯柄略糊，seed 42 时最好。", values: { 产品: "手工粗陶马克杯，哑光釉面", 材质: "粗陶" }, copied: true, sent: true, note: "seed 42 最佳" }],
        sync: "synced",
      }),
      P({
        id: "p-film-poster", vaultId: "v-image", groupId: "g-poster", type: "image",
        title: "电影感人像海报 · 黄昏逆光", summary: "黄昏逆光 + 长焦压缩 + 胶片颗粒，一句话把人拍进故事里。",
        fields: {
          subject: "{{人物}}站在{{场景}}，侧身回望，发丝被风吹起",
          style: "电影感，胶片质感，故事氛围",
          composition: "三分法，人物偏右下，大面积天空",
          lighting: "黄昏逆光，轮廓光勾边，暗部偏青",
          camera: "135mm 长焦压缩，浅景深",
          color: "橙青对比，暗角",
          texture: "35mm 胶片颗粒，轻微光晕",
          detail: "眼神光保留，皮肤质感真实",
        },
        negative: "过度磨皮，塑料感，饱和度过高，畸变，多余人物，文字",
        params: { ratio: "3:4", seed: "77", model: "MJ v6" },
        tagIds: ["t-film", "t-ok"], favorite: true, useCount: 12, lastUsedAt: now - 4 * D,
        createdAt: now - 21 * D, updatedAt: now - 4 * D, sync: "local",
      }),
      P({
        id: "p-min-poster", vaultId: "v-image", groupId: "g-poster", type: "image",
        title: "极简留白海报 · 草稿", summary: "一个物体、一片留白、一行小字。还在调光影层次。",
        fields: {
          subject: "{{物体}}悬浮于画面中央偏上",
          style: "极简风，大面积留白",
          lighting: "单一顶光，柔和投影",
          color: "莫兰迪灰调",
        },
        negative: "复杂背景，多物体，高饱和",
        params: { ratio: "3:4" },
        tagIds: ["t-min", "t-test"], useCount: 3, createdAt: now - 6 * D, updatedAt: now - 26 * H, sync: "local",
      }),
      P({
        id: "p-ad-video", vaultId: "v-video", groupId: "g-ad", type: "video",
        title: "产品宣传片 30s · 三段式分镜", summary: "悬念开场 → 使用场景 → 品牌定格，附带 5 个镜头的分镜表。",
        fields: {
          theme: "{{产品}} 30 秒宣传片：把日常的一分钟拍出仪式感",
          firstFrame: "清晨 6:58，闹钟响起前的安静房间，光线从窗帘缝里渗进来",
          lastFrame: "产品静置于原木桌面，品牌 logo 以烫金质感浮现",
          motion: "缓慢推近 + 升格慢动作点缀", camera: "特写与广角交替，一次航拍俯瞰",
          rhythm: "前 10 秒舒缓，中段渐快，尾段定格", light: "窗边自然光为主，尾段转棚拍暖光",
          transition: "匹配剪辑串联三个场景，结尾黑场 0.5s",
          shots: [
            { id: "s1", label: "开场", content: "闹钟特写，手指按下，升格", secs: "4s" },
            { id: "s2", label: "场景一", content: "厨房晨光，产品第一次入画", secs: "8s" },
            { id: "s3", label: "场景二", content: "通勤路上，航拍城市 transitioning 到手持跟随", secs: "8s" },
            { id: "s4", label: "高潮", content: "快切三连：使用瞬间的特写", secs: "6s" },
            { id: "s5", label: "定格", content: "桌面静物 + logo 浮现", secs: "4s" },
          ],
        },
        params: { duration: "30s", ratio: "16:9", fps: "24fps 电影感", model: "Kling 1.5" },
        tagIds: ["t-film", "t-ok"], favorite: true, useCount: 9, lastUsedAt: now - 2 * D, lastDebugAt: now - 2 * D,
        createdAt: now - 18 * D, updatedAt: now - 2 * D,
        runs: [{ id: "r4", at: now - 2 * D, final: "用详细版投给 Kling，镜头 3 的航拍转手持需要拆成两条生成。", values: { 产品: "手冲咖啡套装" }, copied: true, sent: false, note: "镜头 3 拆分生成效果更好" }],
        sync: "local",
      }),
      P({
        id: "p-doc-video", vaultId: "v-video", groupId: "g-ad", type: "video",
        title: "纪录片式品牌故事 · 开场 10s", summary: "冷调清晨 + 手持跟随 + 环境声先行的纪录片开场模板。",
        fields: {
          theme: "品牌创始人的清晨：先见人，再见事，最后见品牌",
          firstFrame: "冷调清晨的街道，呼出的白气，卷帘门拉开的声音先于画面",
          motion: "手持跟随，轻微呼吸感", camera: "过肩镜头 + 一次低机位广角",
          rhythm: "舒缓，留环境声", light: "冷调清晨，室内暖光对比",
        },
        params: { duration: "10s", ratio: "16:9", fps: "25fps", model: "Sora" },
        tagIds: ["t-film", "t-test"], useCount: 4, createdAt: now - 12 * D, updatedAt: now - 6 * D, sync: "local",
      }),
      P({
        id: "p-translate", vaultId: "v-self", type: "custom",
        title: "学术翻译润色 · 信雅达三步", summary: "先直译、再意译、最后按{{期刊}}风格收口，保留术语表。",
        body: "请把以下{{方向}}文本翻译成学术书面语。\n\n第一步（信）：逐句直译，保留所有术语原貌；\n第二步（达）：在不改变论点的前提下重排句式，使其符合目标语言习惯；\n第三步（雅）：按{{期刊}}的行文风格润色，控制被动语态密度。\n\n术语表：\n{{术语表}}\n\n待翻译文本：\n{{原文}}",
        params: { model: "gpt-4o", temperature: "0.3" },
        tagIds: ["t-ok", "t-long"], useCount: 15, lastUsedAt: now - 8 * D,
        createdAt: now - 22 * D, updatedAt: now - 8 * D, sync: "synced",
      }),
      P({
        id: "p-weekly", vaultId: "v-self", type: "custom",
        title: "周报生成器 · 不卑不亢版", summary: "把流水账输入变成「进展 + 判断 + 需求」三段式周报。",
        body: "把这周的流水账整理成周报，结构固定为三段：\n1. 本周进展：只写有结果的事，每件事一句话 + 一个数字；\n2. 我的判断：对当前方向的一个观察或一个担忧；\n3. 需要的支持：最多两条，明确到人。\n语气不卑不亢，不用「赋能」「抓手」。\n\n流水账：\n{{流水账}}",
        tagIds: ["t-ok"], useCount: 21, lastUsedAt: now - 32 * H,
        createdAt: now - 15 * D, updatedAt: now - 32 * H, sync: "local",
      }),
      P({
        id: "p-inbox-1", vaultId: "v-inbox", type: "custom",
        title: "剪藏：某开源 Agent 框架的系统指令", summary: "从 GitHub 上抄来的，还没消化，周末整理。",
        body: "You are a helpful research assistant. Always cite sources with [n] markers. When uncertain, say so explicitly and propose a verification plan before answering.",
        tagIds: ["t-test"], createdAt: now - 8 * H, updatedAt: now - 8 * H, useCount: 0, sync: "local",
      }),
      P({
        id: "p-old-1", vaultId: "v-inbox", type: "custom",
        title: "（旧）早期文案助手 v0.1", summary: "最早的版本，已经被长文对话模板取代。",
        body: "你是一个文案助手，请帮我写文案。",
        tagIds: [], deletedAt: now - 2 * D, createdAt: now - 50 * D, updatedAt: now - 50 * D, useCount: 64, sync: "local",
      }),
    ],
  };
}
